### ISSUE TITLE
[Feature] Send payment from `externalId`

### ISSUE THREAD

**Issue by gzuuus** [MiguelMedeiros/phoenix-server-js#2]
I was thinking that thanks to the externalIds you could develop a kind of accounting system to have different users/accounts, and they could have access to a certain amount of funds. Do you think this would be an interesting or viable idea? The most basic way to do this, (without any authentication other than providing the externalId) would be to add a new method, for example
 ```
sendLightningInvoiceFromExtId(params: {
    amountSat?: number;
    externalId: string;
    invoice: string;
  }): Promise<PayInvoiceResponse>. 
```
And then limiting the amount of sats it can spend based on the paid invoices that externalId has received. 

If you like the idea I can work on a pr

**Comment by MiguelMedeiros** [comment]
Interesting... just to see if I understood. You would first check if that `externalId` has received payments in your node and then do some accounting to see if it would have enough balance to send payments? Would you use the method: `listIncomingPayments` by passing the `externalId` and validate it?

If that's the case, I think I have no objections. Go ahead!

![image](https://github.com/MiguelMedeiros/phoenix-server-js/assets/5798170/e2c50764-c955-412b-a142-0656b193df00)

**Comment by gzuuus** [comment]
Yes, exactly, that's the idea, so you could have an accounting system over phoenixd, with more development you could make something like lnbits on top of phoenixd 👀

I have thought a bit more about how to implement this and I think it would be necessary to maintain a small DB that associates `paymentId` with `externalId` so that we can know which external id has spent what and do the necessary validations to know the externalId balance. What do you think of this? Is it within the scope of the library? The easiest way would be to use a sqlite DB, or just a json.

**Comment by MiguelMedeiros** [comment]
I thought you would just use an extra command and check it at the time of using it without the need for a database.

Adding a database would be out of scope. In that case it would be interesting to create an application using Phoenix + this npm package on top.

**Comment by gzuuus** [comment]
Yes, I agree. Can you think of a way to validate if funds were used by an externalId without needing a DB to account for this? It would be possible if phoenixd would allow an `externalId` to be attached to an invoice payment.

**Comment by MiguelMedeiros** [comment]
I believe we should adopt the KISS principle: keep it stupid simple. 
We can incorporate this accountability within an additional layer of abstraction and maintain its separation from this library.

**Comment by MiguelMedeiros** [comment]
@gzuuus, I'm going to close this PR for now.

**Comment by gzuuus** [comment]
@MiguelMedeiros Absolutely, let's keep it KISS. I'm going to work on this in a separate repository as it seems like an interesting idea to develop. To give you a bit more of my idea, I want to use nostr as an authentication layer. This way and using the public key as externalId and nip98 (HTTP Auth) we can have a valid e auth system.

**Comment by MiguelMedeiros** [comment]
Nice! Send me the link here when you have something done! 👍

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
davidecoltro, @xannythepleb, @githubber778, @frostRed, @tsnieman, @eddiepease, @lzl, @benoitberenger, @ubbabeck, @willwooten, @jaoleal, @ManUtopiK, @kares, @eamirgh, @psychedelicbart, @felipebrunet, @leonardoli2022, @jackrugile, @thespielplatz, @affektde, @callebtc, @RandyMcMillan, @otech47, @pydraganov, @xucian, @russell-oit, @hynek-jina, @bitcoinuser, @everestuar, @BrutusBondBTC, @Emericus, @prusnak, @detroitpro, @mh-ash, @FelixWeis, @benjaminchodroff, @Junior580, @Triceratroll, @rednaks, @deztin, @CandleHater, @alefvanoon, @JIBSIL, @tiero, @timsta95, @sfr0xyz, @NullRien, @namuyan, @fguisso, @hasundue

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
blakejakopovic, @bithack3r, @gwpl, @maddluxx, @btcforevercat, @DaferSv, @Ele285, @popstardev, @shanelau, @kudlav, @carlosmassa, @greenart7c3, @Perlover, @NORMANCOMICS, @katokishin, @motorina0, @crisdut, @sra, @Christaman2140, @joaqrus, @klouskingsley, @alanStocco, @ion497, @BrunswickBTC, @originalix, @larocquedylan, @mocodesmo, @DmytroShalaiev, @Core2002, @ceramicwhite, @frankhu1089, @USER-id811214293, @Retropex, @GALLAY, @csh2000, @Reaver-ST, @Hakkadaikon, @u20024804, @CodeWarriorr, @dandevri, @dzdidi, @ntotao, @vindard, @cliffhop23, @mhaidarhanif, @Exanteros, @learntheropes, @daiangan, @frederikdiamond, @sorokinvld
